[package]
name = "arkana"
version = "0.1.0"
edition = "2021"
license-file = "MIT"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
crossterm = "0.28"
csv = "1.3.1"
rand = "0.8.5"
ratatui = "0.28.0"
